protoc -I internal/transmitter/proto/ \
  --go_out=internal/transmitter/proto/ \
  --go-grpc_out=internal/transmitter/proto/ \
  --go-grpc_opt=paths=source_relative \
  internal/transmitter/proto/transmitter.proto
