.PHONY: all
all: build_ex00 build_ex01

.PHONY: build_ex00
build_ex00:
	go build cmd/ex00/main.go

.PHONY: build_ex01
build_ex01:
	go build cmd/ex01/main.go

.PHONY: clean
clean:
	@rm -rf main