// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Article struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt time.Time
}
